# Shared Snowflake Profile
shared_snowflake_profile:
  outputs:
    dev:
      account: '{{ env_var(''SNOWFLAKE_ACCOUNT'') }}'
      database: '{{ env_var(''SNOWFLAKE_DATABASE'') }}'
      private_key_path: '{{ env_var(''SNOWFLAKE_PRIVATE_KEY_PATH'') }}'
      role: '{{ env_var(''SNOWFLAKE_ROLE'') }}'
      schema: '{{ env_var(''SNOWFLAKE_SCHEMA'') }}'
      threads: 4
      type: snowflake
      user: '{{ env_var(''SNOWFLAKE_USER'') }}'
      warehouse: '{{ env_var(''SNOWFLAKE_WAREHOUSE'') }}'
  target: dev
